// <auto-generated />
using System;
using Chat.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chat.Infra.Migrations
{
    [DbContext(typeof(ChatContext))]
    partial class ChatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Chat.Domain.AggregateModels.ContactArchivalAggregate.Contact", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid>("ContactUserId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("char(36)")
                        .HasColumnName("ContactUserId");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IsArchived");

                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("Chat.Domain.AggregateModels.ContactArchivalAggregate.ContactArchival", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Chat.Domain.AggregateModels.ReciprocalContactAggregate.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ContactUserId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("char(36)")
                        .HasColumnName("ContactUserId");

                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ContactUserId")
                        .IsUnique();

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("Chat.Domain.QueryEntities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid>("ContactUserId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("char(36)")
                        .HasColumnName("ContactUserId");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsArchived");

                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("Chat.Domain.AggregateModels.ContactArchivalAggregate.Contact", b =>
                {
                    b.HasOne("Chat.Domain.AggregateModels.ReciprocalContactAggregate.Contact", null)
                        .WithOne()
                        .HasForeignKey("Chat.Domain.AggregateModels.ContactArchivalAggregate.Contact", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chat.Domain.AggregateModels.ContactArchivalAggregate.ContactArchival", null)
                        .WithOne("Contact")
                        .HasForeignKey("Chat.Domain.AggregateModels.ContactArchivalAggregate.Contact", "UserId")
                        .HasPrincipalKey("Chat.Domain.AggregateModels.ContactArchivalAggregate.ContactArchival", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chat.Domain.QueryEntities.Contact", b =>
                {
                    b.HasOne("Chat.Domain.AggregateModels.ReciprocalContactAggregate.Contact", null)
                        .WithOne()
                        .HasForeignKey("Chat.Domain.QueryEntities.Contact", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chat.Domain.AggregateModels.ContactArchivalAggregate.ContactArchival", b =>
                {
                    b.Navigation("Contact");
                });
#pragma warning restore 612, 618
        }
    }
}
